"""Markdown -> DOCX conversion and spend estimates. No network."""

from __future__ import annotations

import io

from docx import Document

from smia.cost import add_usage, estimate_usd
from smia.export import markdown_to_docx

MD = """# Playbook — brewbox

## 1. Executive summary [I]
- Short video leads with a **median RE of 0.89** on n=21, directional [T2].
- Athlete-led content carries RE 1.11 [T6].

## 2. Landscape snapshot [D]
| Account | Platform | Posts/wk | Median RE |
|---|---|---|---|
| @nike | instagram | 1.54 | 0.89 |
| @nike | tiktok | 1.00 | 0.785 |

## 9. Example hooks [G]
1. "Drop day is a date, not a vibe." — short_video, AI-generated starting point
2. "Your barista knows your name." — carousel

Plain paragraph with `code` and _italic_.
"""


def test_markdown_to_docx_covers_headings_tables_lists_and_inline():
    data = markdown_to_docx(MD, title="Playbook · brewbox", subtitle="subscription coffee · trailing 90 days")
    doc = Document(io.BytesIO(data))
    texts = [p.text for p in doc.paragraphs]
    assert "Playbook · brewbox" in texts[0]
    assert any(t.startswith("1. Executive summary") for t in texts)
    assert any("Short video leads" in t for t in texts)
    assert len(doc.tables) == 1
    assert doc.tables[0].cell(0, 0).text == "Account" and doc.tables[0].cell(2, 1).text == "tiktok"
    bold = [r.text for p in doc.paragraphs for r in p.runs if r.bold]
    assert "median RE of 0.89" in bold
    assert any("Generated by SMIA" in t for t in texts)


def test_estimate_usd_uses_price_table():
    u = {"input_tokens": 100_000, "output_tokens": 10_000, "cache_read_input_tokens": 500_000, "cache_creation_input_tokens": 50_000}
    assert estimate_usd(u, "claude-opus-5") == 1.3125
    assert estimate_usd(u, "unknown-model") == 0.0


def test_add_usage_accumulates_turns():
    tot: dict = {}
    add_usage(tot, {"input_tokens": 10, "output_tokens": 5})
    add_usage(tot, {"input_tokens": 20, "output_tokens": 1})
    assert tot == {"input_tokens": 30, "output_tokens": 6, "turns": 2}
