"""Report exports: the markdown a report is stored as, rendered to a .docx a marketing lead
can open, forward and annotate. Covers what the templates produce: headings, paragraphs,
bullet and numbered lists, pipe tables, bold and italic, inline code, and [T#] refs."""

from __future__ import annotations

import io
import re
import uuid
from datetime import UTC, datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from sqlalchemy import select

from smia.db.models import Report, Tenant
from smia.db.session import db_session

INLINE_RE = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*|_[^_]+_|`[^`]+`|\[T\d+\])")


def _add_inline(paragraph, text: str) -> None:
    for part in INLINE_RE.split(text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            paragraph.add_run(part[2:-2]).bold = True
        elif (part.startswith("*") and part.endswith("*")) or (part.startswith("_") and part.endswith("_")):
            paragraph.add_run(part[1:-1]).italic = True
        elif part.startswith("`") and part.endswith("`"):
            r = paragraph.add_run(part[1:-1])
            r.font.name = "Consolas"
            r.font.size = Pt(9)
        elif re.fullmatch(r"\[T\d+\]", part):
            r = paragraph.add_run(part)
            r.font.size = Pt(8)
            r.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        else:
            paragraph.add_run(part)


def _table(doc, rows: list[list[str]]) -> None:
    rows = [r for r in rows if r]
    if not rows:
        return
    width = max(len(r) for r in rows)
    t = doc.add_table(rows=len(rows), cols=width)
    t.style = "Light Grid Accent 1"
    for i, r in enumerate(rows):
        for j in range(width):
            cell = t.cell(i, j)
            cell.text = ""
            p = cell.paragraphs[0]
            _add_inline(p, r[j] if j < len(r) else "")
            if i == 0:
                for run in p.runs:
                    run.bold = True
    doc.add_paragraph()


def _split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def markdown_to_docx(markdown: str, *, title: str, subtitle: str = "") -> bytes:
    doc = Document()
    styles = doc.styles
    styles["Normal"].font.name = "Calibri"
    styles["Normal"].font.size = Pt(10.5)

    h = doc.add_heading(title, level=0)
    h.alignment = WD_ALIGN_PARAGRAPH.LEFT
    if subtitle:
        p = doc.add_paragraph()
        r = p.add_run(subtitle)
        r.italic = True
        r.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    lines = markdown.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        s = line.strip()
        if not s:
            i += 1
            continue
        if s.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                row = lines[i].strip()
                if not re.fullmatch(r"\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?", row):
                    rows.append(_split_row(row))
                i += 1
            _table(doc, rows)
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", s)
        if m:
            level = min(len(m.group(1)), 3)
            doc.add_heading(re.sub(r"\*\*|__", "", m.group(2)).strip(), level=level)
            i += 1
            continue
        if s == "---":
            doc.add_paragraph("_" * 40).alignment = WD_ALIGN_PARAGRAPH.CENTER
            i += 1
            continue
        m = re.match(r"^[-*•]\s+(.*)$", s)
        if m:
            _add_inline(doc.add_paragraph(style="List Bullet"), m.group(1))
            i += 1
            continue
        m = re.match(r"^\d+[.)]\s+(.*)$", s)
        if m:
            _add_inline(doc.add_paragraph(style="List Number"), m.group(1))
            i += 1
            continue
        if s.startswith(">"):
            p = doc.add_paragraph()
            _add_inline(p, s.lstrip("> "))
            p.paragraph_format.left_indent = Pt(18)
            i += 1
            continue
        # paragraph: merge consecutive plain lines
        buf = [s]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r"^(#{1,6}\s|[-*•]\s|\d+[.)]\s|\||>|---)", lines[i].strip()):
            buf.append(lines[i].strip())
            i += 1
        _add_inline(doc.add_paragraph(), " ".join(buf))

    footer = doc.add_paragraph()
    r = footer.add_run(f"Generated by SMIA on {datetime.now(UTC).date().isoformat()}. [T#] marks trace to tool results; "
                       "[D] descriptive, [I] interpretive, [G] generative.")
    r.font.size = Pt(8)
    r.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    out = io.BytesIO()
    doc.save(out)
    return out.getvalue()


def report_files(report_id: uuid.UUID) -> tuple[str, bytes, bytes]:
    """(basename, docx_bytes, md_bytes) for a stored report."""
    with db_session() as s:
        report = s.get(Report, report_id)
        if report is None:
            raise LookupError(f"report {report_id} not found")
        tenant = s.get(Tenant, report.tenant_id)
        body, kind, period = report.body, report.kind, report.period
        tname = tenant.name if tenant else "tenant"
        industry = tenant.industry if tenant else ""
    stamp = datetime.now(UTC).date().isoformat()
    base = f"SMIA-{kind}-{re.sub(r'[^A-Za-z0-9_-]+', '-', tname)}-{stamp}"
    title = f"{kind.title()} · {tname}"
    docx = markdown_to_docx(body, title=title, subtitle=f"{industry} · {period}")
    return base, docx, body.encode("utf-8")


def export_report(report_id: uuid.UUID, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    base, docx, md = report_files(report_id)
    p1, p2 = out_dir / f"{base}.docx", out_dir / f"{base}.md"
    p1.write_bytes(docx)
    p2.write_bytes(md)
    return p1, p2


def latest_report_id(tenant_name: str, kind: str | None = None) -> uuid.UUID | None:
    with db_session() as s:
        q = select(Report.id).join(Tenant, Tenant.id == Report.tenant_id).where(Tenant.name == tenant_name)
        if kind:
            q = q.where(Report.kind == kind)
        return s.execute(q.order_by(Report.created_at.desc()).limit(1)).scalar_one_or_none()
